### PR TITLE
Handle FCMv1 responses

### PR DESCRIPTION
**Pull request by moffatman**
They have a different shape. Notifications did go through before this commit, but the system calling common-proxies always got a 502 code.

Since the old API is gonna be turned off in a few days; I didn't handle both; just the new one.

### CODE REVIEW

**Comment by moffatman** [comment]
@p1gp1g  @karmanyaahm

**Comment by p1gp1g** [comment]
Thanks a lot. Is everything correctly working after this commit for you ?

**Comment by moffatman** [comment]
On my dev machine yeah. But I haven't built amd64 Linux yet to try on my actual app. Was waiting for your release as too lazy to set up "go" build system for Linux.

**Comment by p1gp1g** [comment]
I've tested, it works great. Thanks again.

We should probably update the doc to help to set this up. For those looking for the right credentials file:

1. Go to your firebase console, then to IAM-Admin > Service accounts (https://console.cloud.google.com/iam-admin/serviceaccounts)
2. Create a new service account with Firebase Messaging API administration rights
3. Then generate a new key for this account

**Comment by moffatman** [comment]
Thx. is it possible you can do a release to get the linux build?

**Comment by p1gp1g** [comment]
Sure. It is building

**Pull request merged**
